Kernel360/KDEV4-TRACKY-BE

- build.gradle
- tracky-web/src/main/java/kernel360/trackyweb/TrackyWebApplication.java
- tracky-web/src/main/java/kernel360/trackyweb/biz/presentation/BizController.java
- tracky-web/src/main/java/kernel360/trackyweb/config/SwaggerConfig.java
swagger 추가 및 sample api 에 붙는 것 확인완료
> feat: swagger , sample 추가

- .gitignore
- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/entity/CarEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/entity/DeviceEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/entity/DriveEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/entity/GpsHistory.java
- tracky-hub/docker-compose.yml
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/ApiResponse.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/CarOnOffRequest.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/CycleGpsRequest.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/CycleInfoRequest.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/GpsHistoryMessage.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoConsumerService.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/HistoryRepositoty.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/EnvConfig.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQConfig.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/infrastructure/repository/CarRepository.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/infrastructure/repository/HistoryRepository.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/CarInfoController.java
- tracky-hub/src/main/resources/application.properties
- tracky-hub/src/main/resources/application.yml
- Hub 모듈
- RabbitMQ 설정
- 주기 정보 전달 API 구현
- Core 모듈
- 엔티티 연관관계 설정
> RabbitMQ 설정 & 주기 정보 전달 API 구현 & core 모듈 엔티티 연관관계 설정

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
이슈 템플릿 만들었어요
이슈 생성시 템플릿 골라서 사용해주세요
> ENV - 이슈 템플릿 만들었어요

- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/entity/DriveEntity.java
- tracky-web/src/main/java/kernel360/trackyweb/member/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/member/domain/model/MemberPrincipal.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtTokenProvider.java
> WEB - 권한 설정 및 충돌 해결

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CarOnOffRequest.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CycleGpsRequest.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/GpsHistoryRepository.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/infrastructure/repository/RentEntityRepository.java
- tracky-consumer/src/main/resources/application.yml
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/CarEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/DriveEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/GpsHistoryEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/LocationEntity.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/RentEntity.java
- tracky-core/src/main/resources/application.yml
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CarOnOffRequest.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/WebConfig.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CarOnOffRequest.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CycleGpsRequest.java
- tracky-hub/src/main/resources/application.yml
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarDetailResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/RentResponse.java
#65 
- 엔티티 수정 잘 됐는지 꼼꼼하게 봐주세요.
- Cors 설정 잘 됐는지 꼼꼼하게 봐주세요.
- 태클 환영
> feat #65 Hub 모듈 Cors 설정, 엔티티 수정, RabbitMQ 설정 수정

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/TrackyHubApplication.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/infrastructure/repository/CarRepository.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/CarInfoController.java
#68
- 애뮬레이터에 차량 mdn 정보들 반환 api
> HUB - 차량 mdn List 반환 Api

- tracky-consumer/Dockerfile
- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/CarInfoConsumer.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewController.java
- tracky-emulator/src/main/resources/templates/emulator-start-form.html
#61 
화면에서 에뮬레이터 여러대 생성할 수 있도록 개발했습니다.
에뮬레이터 mdn은 허브에서 mdn list를 받아오는 API를 붙여서 
DB에 생성되어 있는 mdn 중에 랜덤으로 골라 생성합니다.
> EMU - feat #61 에뮬레이터 여러대 생성개발

- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/WebConfig.java
> refactor #65 Hub-Cors URL 추가

- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/WebConfig.java
#65 
- Hub 모듈 Cors 설정 Get, Optional 추가
> refactor #65 Cors 메소드 추가

- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/member/PasswordTest.java
- tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/entity/MemberEntity.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtTokenProvider.java
- tracky-web/src/main/java/kernel360/trackyweb/member/presentation/MemberLoginController.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/mapper/RentMapper.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/dto/RentRequest.java
> WEB - #85 JWT 로그인 관련 설정

- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
> WEB - 예약 상태 & 날짜 기준 검색 추가

- tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarUpdateRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
#103 
차량 등록 수정 mdn 관련 로직 수정 & 차량 중복 체크 api 추가
> WEB - 차량 등록 수정 mdn 관련 로직 수정 & 차량 중복 체크 api 추가

- tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarRepositoryImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/CarController.java
- tracky-web/src/main/java/kernel360/trackyweb/car/presentation/dto/CarUpdateRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
#100 
mdn, 차량 상태, 사용목적 필터링 검색 api 추가
-> 추후 query dsl 이 필수일듯...
> 차량 검색 -> mdn, 차량 상태, 사용목적 필터링 검색 api 추가

- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/config/WebConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/application/ReservationService.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/LocationRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationCarRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationDriveRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/infrastructure/repository/ReservationRentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/dto/ReservationDrivingsResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/dto/ReservationWithCarResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/reservation/presentation/rentUserController.java
>  WEB - 차량 이용자 전용 화면 개발

- tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/domain/Statistics.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashDriveRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashRentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardApiDocs.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
> WEB - 통계 관련 api 추가

- tracky-web/src/main/java/kernel360/trackyweb/emitter/EventEmitterService.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/CarRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepository.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/presentation/RentController.java
예약 등록 수정 시 mdn, 예약 상태 select box 처리
> fix: 예약 등록 수정 시 mdn, 예약 상태 select box 처리

- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
- tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/service/RentService.java
> fix @Transactional 추가

- tracky-emulator/build.gradle
- emulator 모듈에 ALB healthcheck 추가
> EMUL - feat emulator에 ALB HealthCheck 추가

- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
에뮬레이터 API 호출 URL 배포 버전으로 수정했습니다.
> refactor-emu

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/dto/CycleGpsRequest.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/config/AsyncConfig.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/presentation/ConsumerController.java
- tracky-consumer/src/main/resources/application.yml
- tracky-core/src/main/resources/application-common.yml
> CONSUMER - hotfix: consumer @Async 부하테스트

- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/GpsHistoryEntity.java
> CONSUMVER - hotfix: 엔티티 생성자 수정

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/common/exception/ConsumerGlobalExceptionHandler.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/common/exception/ErrorResponse.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/config/AsyncConfig.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/GpsHistoryEntity.java
- gpshitory 복합키 제거
- consumer 예외처리 추가
- 잘 봐주세요
> CONSUMER - Hotfix/consumer add log

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/ConsumerService.java
> chore: consumer 로그 추가

- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
> EMU - 거리 계산 수정

- tracky-web/src/main/java/kernel360/trackyweb/config/SecurityConfig.java
- tracky-web/src/main/java/kernel360/trackyweb/member/jwt/JwtAuthenticationFilter.java
#141 
- ALB HealthCheck URI 허용
> #WEB - refactor #141 ALB HealthCheck URI 허용

- tracky-web/src/main/java/kernel360/trackyweb/drivehistory/application/DriveHistoryService.java
- tracky-web/src/main/java/kernel360/trackyweb/drivehistory/infrastructure/repository/GpsHistoryRepository.java
> feat: hotfix

- tracky-web/src/main/java/kernel360/trackyweb/drivehistory/application/DriveHistoryService.java
- tracky-web/src/main/java/kernel360/trackyweb/drivehistory/domain/DriveHistory.java
> feat: history detail 변경

- tracky-consumer/Dockerfile
- tracky-emulator/Dockerfile
- tracky-hub/Dockerfile
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/dto/CarOnOffRequest.java
- tracky-web/Dockerfile
- 각 서버 TimeZone을 Asia/seoul로 변경
- Dockerfile에 TimeZone 설정 추가
> ALL - hotfix: Dockerfile TimeZone 서울 시간으로 수정

- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/exception/RentException.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CarOnOffRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleGpsRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/dto/CycleInfoRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepository.java
> EMU - 위/경도 생성 수정 및 oTime추가

- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/vo/EmulatorInfo.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/TrackyEmulatorApplication.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CycleDataManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/ControlClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CarOnOffRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleGpsRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleInfoRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/TokenRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/domain/EmulatorInstance.java
#160 
core에 추가한 GpsInfo VO를 활용하도록 리팩토링 했습니다.
> EMU - core의 GpsInfo Vo 활용 리팩토링 

- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorException.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorExceptionHandler.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorCode.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorResponse.java
#174 
에뮬레이터 모듈에 Exception Handler 추가해서 예외처리 했습니다
> EMU - 에뮬레이터 예외처리 추가

- tracky-core/src/main/java/kernel360/trackycore/core/common/entity/vo/EmulatorInfo.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/SingleCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceManager.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CarOnOffRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleGpsRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleInfoRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/TokenRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/generator/CycleGpsDataGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/util/RandomLocationGenerator.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorException.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorExceptionHandler.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorCode.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/ErrorResponse.java
#160 
에뮬레이터 모듈의 DTO에 @JsonCreator 추가하여 평면화 ### 작업했습니다.
> EMU - DTO @JsonCreator 추가

- tracky-web/src/main/java/kernel360/trackyweb/member/application/MemberService.java
- tracky-web/src/main/java/kernel360/trackyweb/member/infrastructure/security/jwt/JwtTokenProvider.java
> #153 
> token payload에 bizId를 추가하였습니다
> refactor: token에 bizId 추가

- tracky-consumer/src/main/java/kernel360/trackyconsumer/application/service/MessageListener.java
> hotfix import 경로 수정

- tracky-core/build.gradle
- tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/GpsHistoryEntity.java
#187 
- GpsHistory PK TSID로 변경
- 꼼꼼학 봐주세요
> CORE - GpsHistory PK TSID로 변경

- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
#192 
car searchfilter dsl refactoring
>
> refactor: car searchfilter dsl refactoring

- tracky-web/src/main/java/kernel360/trackyweb/common/filter/HttpLoggingFilter.java
closed #227 
웹 쪽 요청 / 응답 로깅이 필요할 것 같아 코드를 작성했습니다.
이제 요청 하나 보내면, 요청 정보 및 응답 정보가 로깅됩니다.
> WEB - Http 요청/응답 로깅

- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/MdnListRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StartRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/StopRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/TokenRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CarOnOffRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleGpsRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleInfoRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/infrastructure/exception/EmulatorExceptionHandler.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/presentation/view/controller/EmulatorViewController.java
- tracky-emulator/src/main/resources/application.yml
- tracky-emulator/src/main/resources/templates/emulator-start-form.html
#258 
에뮬레이터 주기 데이터에 OTime 추가했습니다.
> EMU - 에뮬레이터 otime 수정

- tracky-core/src/main/resources/application-common.yml
- tracky-web/src/main/java/kernel360/trackyweb/drive/application/DriveService.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/application/dto/request/DriveListRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/domain/DriveHistory.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/domain/GpsData.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/drive/presentation/DriveController.java
#190 
운행기록 검색 api -> 고도화 진행 예정 -> 검색 필터링 누락 추가해야함
-> query dsl 처리로 상세 기록 가져오는 상제 운행기록 api 추가
>
> 운행기록 검색 api -> 고도화 진행 예정

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/CarEntity.java
- tracky-core/src/main/resources/schema.sql
#266 
- 마지막 운행 시간 필드 추가
- 주행 종료 시 Car 엔티티의 last_drive 필드에 추가
- 머지해주세요.
> CORE, CONSUMER - 차량 마지막 운행 시간 필드 추가

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/DriveEntity.java
- tracky-core/src/main/resources/schema.sql
#268 
- 초간 이동거리 80km이상인 경우 집계에서 제외
- merge plz
> CONSUMER - GPS 오류 데이터 제외

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/presentation/ConsumerController.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/CarProvider.java
- tracky-core/src/main/java/kernel360/trackycore/core/infrastructure/repository/CarRepository.java
> feat 모든 mdn, bizID 리스트 API

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/presentation/ConsumerController.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/TrackyHubApplication.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/dto/response/MdnBizResponse.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/presentation/CarInfoController.java
> feat 모든 mdn, bizID 리스트 반환 API

- tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/request/RentCreateRequest.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/domain/util/UuidGenerator.java
> feat: rent address setting

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-core/src/main/resources/application-rabbitmq.yml
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/service/CarInfoProducerService.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQConfig.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/config/RabbitMQProperties.java
- tracky-hub/src/main/resources/application.yml
#268 
- 실시간 경로 추적을 위한 RabbitMQ 추가
- FanoutExchange 추가
>
> HUB - 실시간 경로 추적 Queue 추가

- tracky-hub/src/main/java/kernel360trackybe/trackyhub/application/domain/provider/CarHubDomainProvider.java
> HUB  rent 가능한 차량만 select

- tracky-core/src/main/resources/application-common.yml
> CORE - ALB HealthCheck 허용

- tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/CarProvider.java
- tracky-web/src/main/java/kernel360/trackyweb/car/domain/provider/CarDomainProvider.java
> CORE, WEB  오타 및 안쓰는 메서드 제거

- tracky-web/src/main/java/kernel360/trackyweb/realtime/application/service/MessageListener.java
#275 
- web-queue에서 GPS 데이터 받아 SSE에 전송
>
> WEB -  WebQueue -> WEB -> SSE

- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/CarInstanceFactory/MultiCarInstanceFactory.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/client/CycleRequestClient.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CarOnOffRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleGpsRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/CycleInfoRequest.java
- tracky-emulator/src/main/java/kernel360/trackyemulator/application/service/dto/request/TokenRequest.java
> EMU - DTO평면화 수정

- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
> #293 
> hotfix 차량 정보 조회 오류 해결
>
> WEB - hotfix 차량 정보 조회 오류 해결

- tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/DailyStatisticProvider.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/MonthlyStatisticProvider.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/provider/TimeDistanceProvider.java
core모듈에 daily / monthly statistic provider 추가했습니다!
> Feat: core-statistic provider 추가

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/CarEntity.java
#266
- 시동 on -> 차량 상태 RUNNING
- 시동 off -> 차량 상태 WAITTING
#303 , #308 PR Merge되면 rebase하여 테스트 후 다시 push할 예정입니다!
코드 변경된 부분만 봐주세요!
> CONSUMER - 시동 on/off시 차량 상태 변경

- tracky-core/src/main/java/kernel360/trackycore/core/common/exception/ErrorCode.java
- tracky-core/src/main/java/kernel360/trackycore/core/common/exception/GlobalException.java
- tracky-web/src/main/java/kernel360/trackyweb/common/exception/ErrorResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/common/exception/WebGlobalExceptionHandler.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/RentService.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/application/dto/response/OverlappingRentResponse.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustomImpl.java
> ex) #289 
> WEB - 예약 시, 겹치는 예약 시간 공지
>
> WEB - 예약 시, 겹치는 예약 시간 공지

- tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
- tracky-web/src/main/java/kernel360/trackyweb/car/domain/MdnStatus.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/infrastructure/repository/RentRepositoryCustomImpl.java
X
MdnStatus 누락 추가
rentstatus 관련 querydsl 오류 수정
>
> WEB - MdnStatus 누락 과 서버 에러 사항 수정

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/service/ConsumerService.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/timedistance/domain/provider/TimeDistanceDomainProvider.java
- tracky-core/src/main/java/kernel360/trackycore/core/domain/entity/TimeDistanceEntity.java
#302
- TimeDistance seconds 필드 추가
>
> CORE, CONSUMER - TimeDistance seconds 필드 추가

- tracky-web/src/main/java/kernel360/trackyweb/car/application/CarService.java
- tracky-web/src/main/java/kernel360/trackyweb/car/infrastructure/repository/CarDomainRepositoryCustomImpl.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/application/DashBoardService.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/presentation/DashBoardController.java
- tracky-web/src/main/java/kernel360/trackyweb/rent/domain/provider/RentDomainProvider.java
- tracky-web/src/main/resources/application.yml
> #309
dashboard에 RentStatus를 RETURNED로 업데이트하는 API를 추가했습니다
Provider에 UpdateRentStatus() 메서드 생성했습니다
프론트와 연결 및 테스트 완료했습니다
>
> WEB - dashboard 미반납 현황에서 RentStatus를 반납 완료로 변경하는 기능 추가

- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/CycleInfoRequest.java
- tracky-consumer/src/main/java/kernel360/trackyconsumer/consumer/application/dto/request/GpsHistoryMessage.java
- tracky-hub/src/main/java/kernel360trackybe/trackyhub/hub/application/dto/request/GpsHistoryMessage.java
> HUB, CONSUMER - hotfix 주기정보 dto 수정

- tracky-web/src/main/java/kernel360/trackyweb/drive/infrastructure/repository/DriveDomainRepositoryImpl.java
날짜 필터링이 하루 전날로 계속 조회가 되어서 디버깅했습니다.
> fix : 운행 기록 리스트 디버깅

- tracky-web/src/main/java/kernel360/trackyweb/drive/domain/provider/DriveDomainProvider.java
미사용 메서드떄문에 컴파일 에러 생긴 부분 핫픽스입니다
> hotfix 미사용 메서드 제거

- tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepositoryCustom.java
- tracky-web/src/main/java/kernel360/trackyweb/dashboard/infrastructure/repository/DashGpsHistoryRepositoryCustomImpl.java
> 대시보드 차량 위치 지도 API querydsl 전환

- tracky-emulator/src/main/resources/application.yml
에뮬레이터 모듈 yml 파일에서 DB 연결과 관련된 설정을 제외했습니다.
> 에뮬레이터 db 연결 설정 제외
